version: '3.9'

services:
  db:
    image: postgres:14.2
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_HOST=127.0.0.1
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - db_network

  redis:
    image: redis:7.0.0
    networks:
      - redis_network
    restart: unless-stopped

  flask:
    build:
      context: .
    command: python runserver.py
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/db
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - media_volume:/flask/media
    networks:
      - db_network
      - redis_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
    command: celery -A core.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - flask
    volumes:
      - media_volume:/flask/media
    networks:
      - db_network
      - redis_network
    restart: unless-stopped

volumes:
  db_volume:
  media_volume:

networks:
  db_network:
  redis_network: